### ISSUE TITLE
Partial Access to Package Submodules After Installation

### ISSUE THREAD

**Issue by HakimHafidi** [ShinhwanKang/BeGin#13]
## Environment
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.5]
- Package version: [e.g. 0.1.0]

## Expected Behavior
After installing the package with all dependencies, I should be able to import all submodules as described in the documentation.

## Current Behavior
Despite a successful installation of the 'begin' package, I can only access the 'begin.scenarios.nodes' submodule. Attempts to import from 'begin.algorithms' result in a ModuleNotFoundError.

## Steps to Reproduce
1. Install the package via !pip install git+https://github.com/ShinhwanKang/BeGin.git (after installing prerequisites)
2. Attempt to import the submodule: `from begin.algorithms.piggyback.nodes import *`
3. Observe the `ModuleNotFoundError`

## Possible Solution?
Is there a specific post-installation step required to access all submodules? Or could this be an issue with the package structure on PyPI?

## Additional context
Below is the traceback for the error encountered:

<img width="697" alt="gitGCLissue" src="https://github.com/ShinhwanKang/BeGin/assets/41470578/e9325088-e0f2-4bad-b1f2-7966bdd0180e">

Traceback (most recent call last):
  File "<ipython-input-10-ba246979981c>", line 3, in <module>
    from begin.algorithms.piggyback.nodes import *
ModuleNotFoundError: No module named 'begin.algorithms'

**Comment by ShinhwanKang** [comment]
Hi, @HakimHafidi , sorry for late replying.

I appreciate your interest in our project BeGin.

1. the screenshot you show looks like .ipynb file. Can you show your ipynb file path? (compared to BeGin folder) (which is folder path of your executing file?) I think that the ipynb(executing) file must exist in the same path with 'begin' folder.

2. And, you said that you now installed BeGin 0.1.0. The latest version is 0.2.0! Can you update it?

Thank you.

**Comment by jihoonko** [comment]
We think the issue has been resolved, so we'll close the issue.

**Comment by jihoon-ko** [comment]
It seems the issue has been resolved, so we will close it.
