### ISSUE TITLE
Wrong link in docs

### ISSUE THREAD

**Issue by B-Deprez** [ShinhwanKang/BeGin#15]
Hi. I was browsing the documentation and saw that one of the links to the original paper was incorrect. The link on the TWP page docs/050/twp.rst goes to the GEM paper.

**Comment by ShinhwanKang** [comment]
Hi @B-Deprez , thanks for pointing that out!

You’re right, the link was incorrect. 

We’ve reviewed and merged your pull request #16 , so the link now correctly points to the intended paper in the TWP page (docs/050/twp.rst).

Thank you for your contribution, and feel free to let us know if you spot anything else!

Best regards.

**Comment by jihoon-ko** [comment]
It seems the issue has been resolved, so we will close it.
