### ISSUE TITLE
Difference in joint train performance for aromaticity CL of CGLB and BeGin

### ISSUE THREAD

**Issue by WeiWeic6222848** [ShinhwanKang/BeGin#6]
Hello,

I compared your CGL benchmark BeGin with another CGL benchmark, CGLB (https://proceedings.neurips.cc/paper_files/paper/2022/file/548a41b9cac6f50dccf7e63e9e1b1b9b-Paper-Datasets_and_Benchmarks.pdf), in table 6. the performance of aromaticity-class incremental is reported, in CGLB, this is ~78%.
In BeGin, it is reported as 0.286 in table 5.c. I would expect the result to be more similar.

Kr

**Comment by ShinhwanKang** [comment]
Hi, @WeiWeic6222848 
I think that the reason is that the setting of class-incremental in our benchmark (BeGin) is different from the setting of CGLB. 

please refer the remarks of Section 3.2 in our main paper (https://arxiv.org/pdf/2211.14568.pdf)

Thank you for your attention to BeGin :)

**Comment by WeiWeic6222848** [comment]
Thank you for your reply!

I am aware of the difference between BeGin's class incremental input graph and CGLB's input graph under Node level classification tasks.

In my understanding, CGLB splits the graph into multiple subgraphs, with each task, the graph grows larger. In BeGin, the complete graph is provided at the start, while the loss is only computed for the relevant class.

However, the result I provided is for the Graph classification tasks (Aromaticity-CL), and I think this difference in setting doesn't necessarily apply there, since in the this case the whole graph (atomic-structure?) is used for classification in both frameworks. Sorry if I'm wrong about this.

**Comment by ShinhwanKang** [comment]
Hi, **in the case of graph classification task**, it is right that the whole graph structure is used for classification. 

Thank you :-)

**Comment by WeiWeic6222848** [comment]
thank you for clarification
